.dotnet:
    image: ${IMAGE}
    variables:
        GIT_STRATEGY: none
        GIT_CHECKOUT: "false"
    before_script:
        - export VERSION=0.1.${CI_PIPELINE_ID}
    after_script:
        - ls -lR
